/** Declaration file generated by dts-gen */

export = dymojs;

declare class dymojs {
    constructor(...args: any[]);

    getPrinters(...args: any[]): void;

    print(...args: any[]): void;

}

